//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.SqlClient;

    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cita> cita { get; set; }
        public virtual DbSet<consulta> consulta { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<pago_consulta> pago_consulta { get; set; }
        public virtual DbSet<recetacita> recetacita { get; set; }
        public virtual DbSet<recetavisita> recetavisita { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }

        private static DatabaseEntities objConexionDB = null;
        private SqlConnection con;



        public static DatabaseEntities saberEstado()
        {
            if (objConexionDB == null)
            {
                objConexionDB = new DatabaseEntities();

            }
            return objConexionDB;
        }

        public SqlConnection getCon()
        {
            return con;
        }

        public void closeDB()
        {
            objConexionDB = null;
        }
    }
}
