//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities6 : DbContext
    {
        public DatabaseEntities6()
            : base("name=DatabaseEntities6")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AppointmentDiary> AppointmentDiary { get; set; }
        public virtual DbSet<cita> cita { get; set; }
        public virtual DbSet<Events> Events { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<pago_consulta> pago_consulta { get; set; }
        public virtual DbSet<recetacita> recetacita { get; set; }
        public virtual DbSet<recetavisita> recetavisita { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
    }
}
