//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pago_consulta
    {
        public int idpago { get; set; }
        public long idpaciente { get; set; }
        public int idconsulta { get; set; }
        public bool seguro { get; set; }
        public Nullable<decimal> recibido { get; set; }
        public Nullable<decimal> devuelto { get; set; }
        public int recibido_por { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual paciente paciente { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
