//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyecto_final.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class visita
    {
        public int Id { get; set; }
        public long paciente { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime proxima { get; set; }
        public string motivo { get; set; }
        public string comentario { get; set; }
        public string receta { get; set; }
    }
}
